### ISSUE TITLE
Jobs site ToDo

### ISSUE THREAD

**Issue by Jimeno0** [Geo-Developers/geo-developers-site#5]
- [x] Check both async requests have been finished (data & view loaded) before draw the locations
- Improve the goTo method:
- [x] Create HTML property `data-id` in each panel tab
- [x] By clicking on each panel tab check go over te global data and check if is `on_remote`
- [x] If the target location is not in de main map then switch maps
- [x] Go through the view graphics and check if has the same id than the target panel tab and then go to that graphic
- [x] Make both previous steps works together
- Simpsons main places:
- [x] Simpsons main places:
- [x] Get main places
- [x] Create an array with them
- [x] Choose one of them random, and draw the location there. Then remove it from the list
- [x] Create a popup with the job description for each graphic
- [x] Do not draw popup template in MiniView
- [x] When an element is been expand the previous one should collapse
- [x] Symbols with shadow, Creating with GIMP (be carefull with offsets)
- [x] Buton to switch maps
- Modal
- [x] Set company typeahead 
- [ ] Set company typeahead width
- [x] Geocoder:
  - [x] Set a map with geolocator widget (icono que pueda arrastrar el usuario
  - [x] Put long/lat of the point in a hidden input 
  - [x] Set popUp closed by default 
- [x] Submit:
  - [x] Compile all form data: Serialize jQUery
  - [x] Check all data was introduced: required tag
  - [x] Check email format
  - [x] Sent to de DB: $ajax_POST
- [ ] Add credits to PlayGIS on the simpsonsMap
- [x] Push responsive requirements
- [ ] Do not resize change views button
- [ ] Reload accordion when an offer has been published
- [ ] Cambiar job-id por data-job-id
- [ ] Contemplar que al enviar el form el servidor falle, mandar un mail o avisar al ofertante
- [ ] Callback en la petición de los datos
- [ ] Extraer código del `.tpl` y crear `.js`
